In [1]:
import sys
import math

sys.path.append('/data/work/tme_analysis/uncollided_flux/mc_v_analytic')

import matplotlib.pyplot as plt
import numpy as np
import pyuncf as uf

# Testing pyuncf

Tom Evans

## Mesh Testing

In [2]:
mesh = uf.Mesh(shape=(3,4,5), delta=(0.3,0.2,0.1))

In [3]:
mesh.x

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5])

In [4]:
mesh.y

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [5]:
mesh.z

array([ 0. ,  0.3,  0.6,  0.9])

In [6]:
mesh.num_cells

60

In [7]:
mesh.bounding_box(0, 0, 0)

(array([ 0.,  0.,  0.]), array([ 0.1,  0.2,  0.3]))

In [8]:
mesh.bounding_box(1, 2, 2)

(array([ 0.1,  0.4,  0.6]), array([ 0.2,  0.6,  0.9]))

In [9]:
mesh.shape

(3, 4, 5)

In [10]:
mesh.num_cells_dim(uf.I)

5

In [11]:
mesh.num_cells_dim(uf.J)

4

In [12]:
mesh.num_cells_dim(uf.K)

3

## Source

In [13]:
q = uf.Source((.25,.4,.45))

In [14]:
q.point

array([ 0.25,  0.4 ,  0.45])

## Tracer

In [15]:
tracer = uf.Tracer(q, mesh)

In [16]:
phi = tracer.trace(np.array([0.05, 0.1, 0.15]))

In [17]:
phi

0.22628996065419837

## UNCF

From Analytic Uncollided Flux test in Denovo/uncflux the reference is:

    7.17336835e-05

In [18]:
mesh = uf.Mesh(shape=(10,10,11), delta=(1.2,1.1,1.0), sigma=0.05)

In [19]:
source = uf.Source(point=(9.5,7.2,0.1), strength=2.1*0.5)

In [20]:
uncf = uf.UNCF(source, mesh)

In [21]:
uncf.calc_flux()

In [22]:
flux = uncf.flux

In [24]:
flux[8,4,1] / math.sqrt(4.0 * np.pi)

7.1733683482353978e-05

In [25]:
uncf = uf.UNCF(source, mesh, P=3)

In [26]:
uncf.calc_flux()

In [27]:
flux = uncf.flux

In [28]:
flux[8,4,1] / math.sqrt(4.0 * np.pi)

7.17336622927356e-05